### ISSUE TITLE
Does not follow the docker best-practises of running 1 foreground app per container

### ISSUE THREAD

**Issue by woutersamaey** [vtsykun/packagist-docker#2]
Just wanted to point out that (if I understood this repo correctly) that this Docker deployment does not follow the docker best-practices of running 1 foreground app per container.

It looks like the container runs `supervisor` and uses that to start everything else, instead of creating multiple containers and linking those together.

Was this a conscious decision or is there some reason to it?

**Comment by vtsykun** [comment]
Hi, yes I agree that is not best practises docker usage. it was made for ease of use - so that right away start the container by only a one command.

```
docker run -d --name packeton \
    --mount type=volume,src=packeton-data,dst=/data \
    -p 8080:80 \
    packeton/packeton:latest
```
But at the same time you can use with multiple containers. Example [docker-compose-prod.yml](https://github.com/vtsykun/packeton/blob/master/docker-compose-prod.yml)
